FROM node:gallium-slim
 
RUN apt-get update -yqq && \
apt-get install -yqq --no-install-recommends openjdk-8-jre-headless && \
rm -rf /var/lib/apt/lists/* && \
npm config set unsafe-perm true && \
npm install -g sonarqube-scanner

WORKDIR /usr/src

ENV NODE_PATH "/usr/local/lib/node_modules/"
RUN npm install && npm install -g typescript@3.7.5

COPY . .
