
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.app }}
    name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - name: {{ .Values.portName }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
