export const USER_CREATED_ACTION = 'USER_CREATED';
export const USER_EDITED_ACTION = 'USER_EDITED';
export const USER_DELETED_ACTION = 'USER_DELETED';

export const CORPORATE_EMISSION_CREATED_ACTION = 'CORPORATE_EMISSION_CREATED';
export const CORPORATE_EMISSION_DELETED_ACTION = 'CORPORATE_EMISSION_DELETED';
export const CORPORATE_EMISSION_UPDATED_ACTION = 'CORPORATE_EMISSION_UPDATED';

export const TARGET_CREATED_ACTION = 'TARGET_CREATED';
export const TARGET_UPDATED_ACTION = 'TARGET_UPDATED';
export const TARGET_DELETED_ACTION = 'TARGET_DELETED';

export const COMPANY_RELATIONSHIP_CREATED_ACTION =
  'COMPANY_RELATIONSHIP_CREATED';
export const COMPANY_RELATIONSHIP_UPDATED_ACTION =
  'COMPANY_RELATIONSHIP_UPDATED';
export const COMPANY_RELATIONSHIP_DELETED_ACTION =
  'COMPANY_RELATIONSHIP_DELETED';

export const EMISSION_ALLOCATION_CREATED_ACTION =
  'EMISSION_ALLOCATION_CREATED_ACTION';
export const EMISSION_ALLOCATION_UPDATED_ACTION =
  'EMISSION_ALLOCATION_UPDATED_ACTION';
export const EMISSION_ALLOCATION_DELETED_ACTION =
  'EMISSION_ALLOCATION_DELETED_ACTION';

export const COMPANY_SECTOR_UPDATED_ACTION = 'COMPANY_SECTOR_UPDATED';

export const SOLUTION_INTERESTS_UPDATED_ACTION = 'SOLUTION_INTERESTS_UPDATED';

export const COMPANY_CREATED_ACTION = 'COMPANY_CREATED';

export const SECTOR_CREATED_ACTION = 'SECTOR_CREATED';

export const COMPANY_SECTOR_CREATED_ACTION = 'COMPANY_SECTOR_CREATED';

export const COMPANY_UPDATED_ACTION = 'COMPANY_UPDATED';

export const DATA_SHARE_REQUEST_INSERTED = 'DATA_SHARE_REQUEST_INSERTED';

export type AuditActionType =
  | typeof USER_CREATED_ACTION
  | typeof USER_EDITED_ACTION
  | typeof USER_DELETED_ACTION
  | typeof CORPORATE_EMISSION_CREATED_ACTION
  | typeof CORPORATE_EMISSION_DELETED_ACTION
  | typeof CORPORATE_EMISSION_UPDATED_ACTION
  | typeof TARGET_CREATED_ACTION
  | typeof TARGET_UPDATED_ACTION
  | typeof TARGET_DELETED_ACTION
  | typeof COMPANY_RELATIONSHIP_CREATED_ACTION
  | typeof COMPANY_RELATIONSHIP_UPDATED_ACTION
  | typeof COMPANY_RELATIONSHIP_DELETED_ACTION
  | typeof EMISSION_ALLOCATION_CREATED_ACTION
  | typeof EMISSION_ALLOCATION_UPDATED_ACTION
  | typeof EMISSION_ALLOCATION_DELETED_ACTION
  | typeof COMPANY_SECTOR_UPDATED_ACTION
  | typeof SOLUTION_INTERESTS_UPDATED_ACTION
  | typeof COMPANY_CREATED_ACTION
  | typeof SECTOR_CREATED_ACTION
  | typeof COMPANY_SECTOR_CREATED_ACTION
  | typeof COMPANY_UPDATED_ACTION
  | typeof DATA_SHARE_REQUEST_INSERTED;
