export const DEFAULT_ATTEMPTS = 5;
export const DEFAULT_TIMEOUT = 20000;

export const MAX_NUMBER_OF_EMAIL_JOBS = 1000;
export const MAX_EMAILS_JOBS_DURATION = 1000;
// QUEUES
export const EMAIL_SEND_QUEUE_NAME = 'SEND_EMAIL';
export const USER_QUEUE_NAME = 'USER';
export const COMPANY_QUEUE_NAME = 'COMPANY';
export const COMPANY_RELATIONSHIP_QUEUE_NAME = 'COMPANY_RELATIONSHIP';
export const CORPORATE_EMISSION_QUEUE_NAME = 'CORPORATE_EMISSION';
export const TARGET_QUEUE_NAME = 'TARGET';
export const EMISSION_ALLOCATION_QUEUE_NAME = 'EMISSION_ALLOCATION';
// PROCESSORS
export const SEND_MULESOFT_EMAIL_PROCESSOR = 'SEND_MULESOFT_EMAIL';
export const SEND_HUBSPOT_EMAIL_PROCESSOR = 'SEND_HUBSPOT_EMAIL';

export const COMPANY_CREATED = 'COMPANY_CREATED';
export const COMPANY_UPDATED = 'COMPANY_UPDATED';

export const USER_CREATED = 'USER_CREATED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';
export const HUBSPOT_CONTACT_CREATED = 'HUBSPOT_CONTACT_CREATED';

export const CORPORATE_EMISSION_CREATED = 'CORPORATE_EMISSION_CREATED';
export const CORPORATE_EMISSION_UPDATED = 'CORPORATE_EMISSION_UPDATED';
export const CORPORATE_EMISSION_DELETED = 'CORPORATE_EMISSION_DELETED';

export const TARGET_CREATED = 'TARGET_CREATED';
export const TARGET_UPDATED = 'TARGET_UPDATED';
export const TARGET_DELETED = 'TARGET_DELETED';

export const COMPANY_RELATIONSHIP_CREATED = 'COMPANY_RELATIONSHIP_CREATED';

export const EMISSION_ALLOCATION_CREATED = 'EMISSION_ALLOCATION_CREATED';
