enum SbtiSystemName {
  AIR_FREIGHT_TRANSPORT,
  BANKS_INSURANCE,
  CHEMICALS,
  CONSTRUCTION_ENGINEERING,
  CONSTRUCTION_MATERIALS,
  ELECTRICAL_EQUIPMENT_MACHINERY,
  FOREST_PAPER_PRODUCTS,
  GROUND_TRUCK_TRANSPORT,
  MARITIME_TRANSPORT,
  OIL_GAS,
  PROFESSIONAL_SERVICES,
  RETAILING,
  SOFTWARE_AND_SERVICE,
  TECHNOLOGY_HARDWARE_EQUIPMENT,
  TRADING_COMPANY_COMMERCIAL_SERVICE,
  WATER_UTILITIES,
}
