type AbsoluteTarget {
  scope1And2Year: Int!
  scope1And2Reduction: Float!
  scope3Year: Int
  scope3Reduction: Float
  strategy: TargetStrategyType!
  includeCarbonOffset: Boolean!
  scope1And2PrivacyType: TargetPrivacyType
  scope3PrivacyType: TargetPrivacyType
  companyId: String!
}
