type ComanyDataPrivacyCompleteness {
  isComplete: Boolean!
  companyId: UUID!
  numCorporateEmissionAccessMissing: Int!
  numIntensityTargetPrivacyTypeMissing: Int!
  numAbsoluteTargetPrivacyTypeMissing: Int!
}
